---
name: Label auto-merge PRs

on:
  pull_request_target:
    types: [auto_merge_enabled, auto_merge_disabled]

env:
  LABEL_NAME: 'automerge :bell:'

permissions:
  contents: read

jobs:
  add-remove-label:
    permissions:
      issues: write  # for dependabot to enable auto-label
      repository-projects: write  # for dependabot to enable auto-label
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - name: Update label
        run: |
          if [[ "${{ github.event.action }}" == "auto_merge_enabled" ]]; then
            gh pr edit ${{ github.event.pull_request.number }} --repo ${{ github.repository }} --add-label "${{ env.LABEL_NAME }}"
          elif [[ "${{ github.event.action }}" == "auto_merge_disabled" ]]; then
            gh pr edit ${{ github.event.pull_request.number }} --repo ${{ github.repository }} --remove-label "${{ env.LABEL_NAME }}"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
